{{- if and .Values.persistence.enabled .Values.persistence.backup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "evcc.fullname" . }}-litestream
  labels:
    {{- include "evcc.labels" . | nindent 4 }}
data:
  litestream.yml: |
    dbs:
      - path: {{ .Values.persistence.databasePath }}
        replica:
          path: {{ .Values.persistence.backup.replicaPath }}
      - path: {{ .Values.persistence.databasePath }}
        monitor-interval: 1m
        checkpoint-interval: 1m
        replica:
          sync-interval: 1h
          {{- if eq .Values.persistence.backup.type "s3" }}
          type: s3
          {{- if .Values.persistence.backup.s3.url }}
          url: {{ .Values.persistence.backup.s3.url }}
          {{else}}
          region: {{ .Values.persistence.backup.s3.region }}
          endpoint: {{ .Values.persistence.backup.s3.endpoint }}
          bucket: {{ .Values.persistence.backup.s3.bucket }}
          force-path-style: {{ .Values.persistence.backup.s3.forcePathStyle | default false }}
          sign-payload: {{ .Values.persistence.backup.s3.signPayload | default false }}
          {{ end}}
        path: {{ .Values.persistence.backup.s3.path }}

{{- end }}

